### ISSUE TITLE
Sanitize text on API request in server

### ISSUE THREAD

**Issue by abhisekp** [gitterHQ/gitter#1009]
The response to the following API call results in a syntax error in gitter server.

### API call
```text
POST /rooms/:roomId/chatMessages

{"text": "\:"}
```

### Response
```text
SyntaxError: Unexpected token :
   at Object.parse (native)
   at parse (/opt/gitter/gitter-webapp/node_modules/body-parser/lib/types/json.js:88:17)
   at /opt/gitter/gitter-webapp/node_modules/body-parser/lib/read.js:116:18
   at invokeCallback (/opt/gitter/gitter-webapp/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
   at done (/opt/gitter/gitter-webapp/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
   at IncomingMessage.onEnd (/opt/gitter/gitter-webapp/node_modules/body-parser/node_modules/raw-body/index.js:308:7)
   at IncomingMessage.EventEmitter.emit (events.js:92:17)
   at _stream_readable.js:920:16
   at process._tickDomainCallback (node.js:459:13)
````

**Comment by abhisekp** [comment]
This also happens using single quote instead of double quote while sending the RAW JSON request body since single quotes are invalid in JSON.

### API Response
```text
SyntaxError: Unexpected token '
   at Object.parse (native)
   at parse (/opt/gitter/gitter-webapp/node_modules/body-parser/lib/types/json.js:88:17)
   at /opt/gitter/gitter-webapp/node_modules/body-parser/lib/read.js:116:18
   at invokeCallback (/opt/gitter/gitter-webapp/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
   at done (/opt/gitter/gitter-webapp/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
   at IncomingMessage.onEnd (/opt/gitter/gitter-webapp/node_modules/body-parser/node_modules/raw-body/index.js:308:7)
   at IncomingMessage.EventEmitter.emit (events.js:92:17)
   at _stream_readable.js:920:16
   at process._tickDomainCallback (node.js:459:13)
```
