### ISSUE TITLE
Hide room throws error

### ISSUE THREAD

**Issue by MadLittleMods** [gitterHQ/gitter#1187]
On the old left menu, the "hide" action under the "x" icon throws an error in the console and does nothing.

Moved from here: https://github.com/gitterHQ/desktop/issues/128

**Comment by iheartkode** [comment]
Same issue on Chrome.

`vendor.js:5 Unhandled rejection Error: SyntaxError: Unexpected token O
    at c (https://cdn03.gitter.im/_s/0ac7125/js/router-app.js:2:1606)
    at Object.t.ajax.error (https://cdn03.gitter.im/_s/0ac7125/js/router-app.js:2:2102)
    at h (https://cdn02.gitter.im/_s/0ac7125/js/vendor.js:3:12633)
    at Object.d.fireWith (https://cdn02.gitter.im/_s/0ac7125/js/vendor.js:3:13440)
    at n (https://cdn02.gitter.im/_s/0ac7125/js/vendor.js:4:17849)
    at XMLHttpRequest.<anonymous> (https://cdn02.gitter.im/_s/0ac7125/js/vendor.js:4:23051)`

**Comment by RoboMWM** [comment]
Had same issue on IE and Edge, but it seems to have disappeared after several hours.

**Comment by theflametrooper** [comment]
Still an issue on the webapp in chrome it seems.

**Comment by hallaathrad** [comment]
If it helps, if you click on hide while using Gitter in the browser, the item disappears after refreshing.
It must have something to do with the page being updated.

**Comment by Toxantron** [comment]
@MadLittleMods was able to help me with a workaround similar to @hallaathrad 

1. Press hide (which does nothing)
2. Select a new room to update URL
3. Refresh the app
4. Make sure to refresh / sign-out all open instances of gitter, otherwise if you click it again you are right back where you started.

**Comment by MadLittleMods** [comment]
The new left menu was rolled out to everyone a while ago which does not reproduce this bug.
