### ISSUE TITLE
Can't Delete a Room

### ISSUE THREAD

**Issue by atjonathan** [gitterHQ/gitter#1261]
After waiting 8 seconds, when you click the delete button - nothing happens.

This error is displayed in the console:
![image](https://cloud.githubusercontent.com/assets/11198912/15438017/1ed1dc7e-1ec2-11e6-9498-c59edd88491a.png)

**Comment by MadLittleMods** [comment]
I can reproduce

```
vendor.js:6161 Unhandled rejection Error: Internal Server Error
    at c (https://cdn03.gitter.im/_s/S76c654a/js/router-chat.js:3:1618)
    at Object.o.ajax.error (https://cdn03.gitter.im/_s/S76c654a/js/router-chat.js:3:2114)
    at h (https://cdn02.gitter.im/_s/S76c654a/js/vendor.js:3:12500)
    at Object.d.fireWith (https://cdn02.gitter.im/_s/S76c654a/js/vendor.js:3:13307)
    at n (https://cdn02.gitter.im/_s/S76c654a/js/vendor.js:4:17743)
    at XMLHttpRequest.<anonymous> (https://cdn02.gitter.im/_s/S76c654a/js/vendor.js:4:22945)
```

**Comment by suprememoocow** [comment]
Thanks for the report @theflametrooper, this is a bug in our staging environment. I've pushed a fix and it should be in fairly soon.
