### ISSUE TITLE
"Unable to add ..." when inviting people after creating a new room associated with a GitHub repository

### ISSUE THREAD

**Issue by vinniefalco** [gitterHQ/gitter#1401]
"Unable to add ..." when inviting people after creating a new room associated with a GitHub repository

Says it all:
![gitter](https://cloud.githubusercontent.com/assets/1503976/17989276/2f21745c-6afa-11e6-9ec3-132a28b69a03.png)

---

See :point_up: [August 25, 2016 6:25 PM](https://gitter.im/gitterHQ/gitter?at=57bf7e641237f2f24463128b)

**Comment by Fuzzyma** [comment]
have the same issue - whats the status on this?

**Comment by mydigitalself** [comment]
Seems it was fixed a long time ago, do you see any errors in your console, could be different issue. Please share as much as possible.

**Comment by jmcmurry** [comment]
I'm having the same problem too. I'm having it on the desktop app and on the webapp. I'm getting a 403 Forbidden on post (Unhandled rejection). Here's the thread output, if useful.

````js
POST https://gitter.im/api/v1/rooms/58fe6501d73408ce4f5ab2d1/invites 403 (Forbidden)
(anonymous)            @ vendor.js:sourcemap:15
send                         @ vendor.js:sourcemap:4
ajax                          @ vendor.js:sourcemap:4
(anonymous)            @ vendor.js:sourcemap:9
s                               @ vendor.js:sourcemap:6
o._resolveFromExecutor @ vendor.js:sourcemap:5
o                               @ vendor.js:sourcemap:5
(anonymous)             @ vendor.js:sourcemap:9
o                               @ vendor.js:sourcemap:5
o._settlePromiseFromHandler @ vendor.js:sourcemap:5
o._settlePromise      @ vendor.js:sourcemap:5
o._settlePromiseCtx @ vendor.js:sourcemap:5
r._drainQueue          @ vendor.js:sourcemap:5
r._drainQueues        @ vendor.js:sourcemap:5
drainQueues            @ vendor.js:sourcemap:5
(anonymous)            @ vendor.js:sourcemap:5
vendor.js:sourcemap:15 Unhandled rejection Error: Forbidden
    at r (https://cdn02.gitter.im/_s/88aafe0/js/vendor.js:9:21524)
    at Object.error (https://cdn02.gitter.im/_s/88aafe0/js/vendor.js:9:23152)
    at l (https://cdn02.gitter.im/_s/88aafe0/js/vendor.js:3:14505)
    at Object.fireWith [as rejectWith] (https://cdn02.gitter.im/_s/88aafe0/js/vendor.js:3:15322)
    at n (https://cdn02.gitter.im/_s/88aafe0/js/vendor.js:4:20053)
    at XMLHttpRequest.<anonymous> (https://cdn02.gitter.im/_s/88aafe0/js/vendor.js:4:25961)
    at XMLHttpRequest.r (https://cdn02.gitter.im/_s/88aafe0/js/vendor.js:14:30241)
e.(anonymous function) @ vendor.js:sourcemap:15
R                          @ vendor.js:sourcemap:6
T                          @ vendor.js:sourcemap:6
S                          @ vendor.js:sourcemap:6
e._notifyUnhandledRejection @ vendor.js:sourcemap:6
r._drainQueue       @ vendor.js:sourcemap:5
r._drainQueues     @ vendor.js:sourcemap:5
drainQueues        @ vendor.js:sourcemap:5
(anonymous)        @ vendor.js:sourcemap:5
````

**Comment by MadLittleMods** [comment]
@jmcmurry Please create a new issue instead of commenting on an old issue that probably had a separate cause (already had a fix).
