### ISSUE TITLE
I cannot create a new gitter community

### ISSUE THREAD

**Issue by felipevolpone** [gitterHQ/gitter#1440]
I'm getting this error on the Chrome console, when I click on the "create and finish" button.

```javascript
Unhandled rejection Error: Bad Request
    at c (https://cdn03.gitter.im/_s/9944e87/js/router-app.js:2:12458)
    at Object.error (https://cdn03.gitter.im/_s/9944e87/js/router-app.js:2:12954)
    at l (https://cdn02.gitter.im/_s/9944e87/js/vendor.js:3:14505)
    at Object.fireWith [as rejectWith] (https://cdn02.gitter.im/_s/9944e87/js/vendor.js:3:15322)
    at n (https://cdn02.gitter.im/_s/9944e87/js/vendor.js:4:20053)
    at XMLHttpRequest.<anonymous> (https://cdn02.gitter.im/_s/9944e87/js/vendor.js:4:25961)
```

**Comment by MadLittleMods** [comment]
@felipevolpone Can you share the request payload of the POST request(network tab of the developer tools) when you push the "Create and Finish" button?

![](http://i.imgur.com/dk9cgUy.png)

**Comment by felipevolpone** [comment]
@MadLittleMods I revoked the gitter access to my github account, try it again and it worked. Thanks for the quickly answer
