### ISSUE TITLE
Crash after Exiting the Gitter Desktop client on Ubuntu 16.04

### ISSUE THREAD

**Issue by C-F-4** [gitterHQ/gitter#1564]
Gitter Desktop Client always crashes with an Error. At first I thought it was a couple of times maybe, but now that I monitored the crashes, it's everytime.

Here's the crash file:
[Uploading _opt_Gitter_linux64_Gitter.1000.crash.txt…]()

**Comment by MadLittleMods** [comment]
`Gitter crashed with SIGSEGV`

The crash log isn't illuminating what is going wrong from a quick glance.

```
 Thread 1 (Thread 0x7ff26cc84a40 (LWP 24168)):
 #0  0x00000000017e13ec in ?? ()
 No symbol table info available.
 #1  0x0000000002747d9d in ?? ()
 No symbol table info available.
 #2  0x0000000002747d8c in ?? ()
 No symbol table info available.
 #3  0x0000000002747d8c in ?? ()
 No symbol table info available.
 #4  0x0000000002747d8c in ?? ()
 No symbol table info available.
 #5  0x0000000002747d8c in ?? ()
 No symbol table info available.
 #6  0x000000000274781b in ?? ()
 No symbol table info available.
 #7  0x0000000002743db3 in ?? ()
 No symbol table info available.
 #8  0x0000000002743e29 in ?? ()
 No symbol table info available.
 #9  0x000000000271e226 in ?? ()
 No symbol table info available.
 #10 0x000000000271e310 in ?? ()
 No symbol table info available.
 #11 0x00000000028698b7 in ?? ()
 No symbol table info available.
 #12 0x000000000357f2f7 in ?? ()
 No symbol table info available.
 #13 0x00000000029dfca8 in ?? ()
 No symbol table info available.
 #14 0x00000000029e0b85 in ?? ()
 No symbol table info available.
 #15 0x00000000029df860 in ?? ()
 No symbol table info available.
 #16 0x00000000006a7e58 in ?? ()
 No symbol table info available.
 #17 0x00007ff266b30830 in __libc_start_main (main=0x6a7e20, argc=4, argv=0x7ffcf579e298, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffcf579e288) at ../csu/libc-start.c:291
         result = <optimized out>
         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, -9032465997665193363, 6663472, 140724426891920, 0, 0, 9034168109727953517, 9026048809929486957}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x7ffcf579e2c0, 0x7ff26cd4e168}, data = {prev = 0x0, cleanup = 0x0, canceltype = -176561472}}}
         not_first_call = <optimized out>
 #18 0x000000000065ad59 in _start ()
 No symbol table info available.
Title: Gitter crashed with SIGSEGV
UnreportableReason: This is not an official Ubuntu package. Please remove any third party package and try again.
UpgradeStatus: No upgrade log present (probably fresh install)
_MarkForUpload: True
```

**Comment by C-F-4** [comment]
So SIGSEGV everytime? There has to be something it's accessing wrong? Is it something that's just happening on my system?

**Comment by MadLittleMods** [comment]
@C-F-4 The logs don't give me enough info to figure out what is going wrong. 

Perhaps related to

 - https://github.com/gitterHQ/desktop/issues/33
 - https://github.com/gitterHQ/gitter/issues/871

**Comment by C-F-4** [comment]
@MadLittleMods it's not #871  but it could be same as desktop#33 "assuming" Closing Window is actually exiting Gitter Client from the Tray Icon, not just hiding it from the desktop(leaving app run in the background). Following the Issue threads linked with #33 I'd say the bug exists in all the Distros.
