### ISSUE TITLE
Trouble with community for an organization

### ISSUE THREAD

**Issue by OndrejMarsalek** [gitterHQ/gitter#1617]
I am having trouble with a community for one of my organizations. When I click on the org in the list under "YOUR ORGANISATIONS" I get a pop up to create a room because "it does not yet exist", but when I click "CREATE", nothing happens and the pop up stays up. This appears in the console, though:

```
Unhandled rejection Error: Not Found
    at i (https://cdn02.gitter.im/_s/b230113/js/vendor.js:9:12802)
    at Object.error (https://cdn02.gitter.im/_s/b230113/js/vendor.js:9:14430)
    at l (https://cdn02.gitter.im/_s/b230113/js/vendor.js:3:14505)
    at Object.fireWith [as rejectWith] (https://cdn02.gitter.im/_s/b230113/js/vendor.js:3:15322)
    at n (https://cdn02.gitter.im/_s/b230113/js/vendor.js:4:20053)
    at XMLHttpRequest.<anonymous> (https://cdn02.gitter.im/_s/b230113/js/vendor.js:4:25961)
    at XMLHttpRequest.i (https://cdn02.gitter.im/_s/b230113/js/vendor.js:14:16247)
```

If I go to the address directly at https://gitter.im/MarklandGroup I get the expected page, but the "Home" room does not seem to work and appending `/home` to the URL results in a 404 error page, unlike for other communities.

**Comment by mydigitalself** [comment]
@OndrejMarsalek what do you see when you visit https://gitter.im/MarklandGroup  ?

**Comment by OndrejMarsalek** [comment]
I see the expected page listing two private rooms that I created for two private repositories. In the list on the left there is "Home" and the two rooms, but clicking home does not change the URL, unlike under other orgs.

**Comment by mydigitalself** [comment]
`Home` is the listing page...

**Comment by OndrejMarsalek** [comment]
I realize that, but for other orgs, `/home` get appended to the URL or I can visit that URL directly and it works. For this one, that page is 404: https://gitter.im/MarklandGroup/home Not a problem itself, but it indicates that something is off.

**Comment by mydigitalself** [comment]
Right, I see - yeah there's probably some corrupt data somewhere.

**Comment by mydigitalself** [comment]
@OndrejMarsalek right, figured pretty much everything out.

/home is for legacy communities after we introduced the ability to create any community (i.e. not just on GitHub)

so /Markland is showing you the correct stuff. You can create more rooms for it using the `Add a room` button

The modal you are seeing that the room doesn't exist when you click on it in `Your Organisations` is indeed a bug, as we don't support creating rooms with just a single path name any more.

**Comment by OndrejMarsalek** [comment]
Thanks for the explanation. I there something I can/should do to "convert" legacy communities to the new way?

**Comment by MadLittleMods** [comment]
@mydigitalself Do you want us to remove the "Your Organisations" section from the bottom of the "All Conversations" section of the left menu?

**Comment by OndrejMarsalek** [comment]
From a user's perspective, that would be my preference. Considering that communities are not tied to orgs anymore and that they can be found in a separate list, I think the current list of orgs is just confusing (in addition to being broken).

**Comment by c-georgen** [comment]
@MadLittleMods I'm having the same problem with one of my communities, let me know if I can provide any info that would be helpful

**Comment by MadLittleMods** [comment]
@c-georgen Same solution? Don't use "Your Organisations" and you can't create root rooms anymore.

Use the "+" on the menu bar (very left) to create a community and the "Add a room" button at the bottom of the conversation list to create a room under a community.

**Comment by c-georgen** [comment]
@MadLittleMods Right, everything seems fine adding rooms to the community and accessing them. It's just that popup modal for "Your Organizations" doesn't work. Echoing what @OndrejMarsalek said, "Your Organizations" probably should be removed.
