### ISSUE TITLE
clicking the star at e.g. https://gitter.im/gitterHQ/home fails to favour e.g. gitterHQ

### ISSUE THREAD

**Issue by grahamperrin** [gitterHQ/gitter#1632]
## Steps

1. browse to https://gitter.im/gitterHQ/home
2. click the star

## Expected

- gitterHQ to the left of the minibar a.k.a. shortcut bar **and**
- a change of colour of the star

## Actual result

https://gitter.im/gitterHQ/gitter?at=58d12689a88e33407107b14c @mydigitalself confirmed: 

> … javascript error

```
vendor.js:5 Unhandled rejection Error: Not Found
    at i (https://cdn02.gitter.im/_s/S956ddab/js/vendor.js:9:12802)
    at Object.error (https://cdn02.gitter.im/_s/S956ddab/js/vendor.js:9:14430)
    at l (https://cdn02.gitter.im/_s/S956ddab/js/vendor.js:3:14505)
    at Object.fireWith [as rejectWith] (https://cdn02.gitter.im/_s/S956ddab/js/vendor.js:3:15322)
    at n (https://cdn02.gitter.im/_s/S956ddab/js/vendor.js:4:20053)
    at XMLHttpRequest.<anonymous> (https://cdn02.gitter.im/_s/S956ddab/js/vendor.js:4:25961)
```

## Workaround

>  - … click on Groups icon (the fourth one down) 
> 
> - drag GitterHQ onto the minibar …

**Comment by grahamperrin** [comment]
Thanks. Incidentally I do not find the workaround applicable with (globe icon) https://gitter.im/BSDs

**Comment by grahamperrin** [comment]
Thanks. My mistake. (I counted down the wrong column.)
