### ISSUE TITLE
Full Path Disclosure

### ISSUE THREAD

**Issue by ajdumanhug** [gitterHQ/gitter#1693]
Hi,

When you requested for a non-existing page on some Gitter domains, it will disclose an error which includes the Full Path or the web root.

**Proof:**
Go to these websites and you'll see the error:
- https://beta.gitter.im/hey
- https://cdn01-beta.gitter.im/hey

**Errors:**
```
StatusError: Not Found
    at /opt/gitter/gitter-webapp/server/services/room-context-service.js:41:28
    at wrapped (/opt/gitter/gitter-webapp/node_modules/newrelic/lib/transaction/tracer/index.js:183:28)
    at Promise.linkTransaction (/opt/gitter/gitter-webapp/node_modules/newrelic/lib/instrumentation/promise.js:273:65)
    at Promise.wrapped [as __NR_wrapper] (/opt/gitter/gitter-webapp/node_modules/newrelic/lib/transaction/tracer/index.js:183:28)
    at __NR_wrappedThenHandler (/opt/gitter/gitter-webapp/node_modules/newrelic/lib/instrumentation/promise.js:445:26)
    at tryCatcher (/opt/gitter/gitter-webapp/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/gitter/gitter-webapp/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/opt/gitter/gitter-webapp/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/opt/gitter/gitter-webapp/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/opt/gitter/gitter-webapp/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/opt/gitter/gitter-webapp/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/opt/gitter/gitter-webapp/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/opt/gitter/gitter-webapp/node_modules/bluebird/js/release/async.js:17:14)
    at Immediate.wrapped [as _onImmediate] (/opt/gitter/gitter-webapp/node_modules/newrelic/lib/transaction/tracer/index.js:183:28)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

I tried to do the same thing on the main website of Gitter but doesn't show any errors:
- https://gitter.im/hey

**Attack Scenario:**
If the web root is getting leaked, attackers may abuse the knowledge and use it in combination with file inclusion vulnerabilities to steal configuration files regarding the web application or the rest of the operating system.

**Remediation**
Make sure no auto-generated errors are shown to the end user.

Best Regards,

Allan

**Comment by ajdumanhug** [comment]
Hi @suprememoocow,

Brian resolved this issue on HackerOne.

Allan
