### ISSUE TITLE
"Unable to add ..." when inviting people after creating a new room associated with a GitHub repository

### ISSUE THREAD

**Issue by jmcmurry** [gitterHQ/gitter#1709]
Identical to #1401, potentially with a different cause. Making new issue per request of @mydigitalself.

"Unable to add ..." when inviting people after creating a new room associated with a GitHub repository; in this case a private repo, though I've not tested to see whether public/private makes a difference.

<img width="363" alt="screen shot 2017-05-23 at 11 12 39 pm" src="https://cloud.githubusercontent.com/assets/3658863/26389188/713052bc-400d-11e7-868c-61e49d6a3364.png">

I'm having the identical issue on the desktop app and on the webapp. 
On the latter, I'm getting a 403 Forbidden on post (Unhandled rejection). Here's the thread output, if useful.

````js
POST https://gitter.im/api/v1/rooms/58fe6501d73408ce4f5ab2d1/invites 403 (Forbidden)
(anonymous)            @ vendor.js:sourcemap:15
send                         @ vendor.js:sourcemap:4
ajax                          @ vendor.js:sourcemap:4
(anonymous)            @ vendor.js:sourcemap:9
s                               @ vendor.js:sourcemap:6
o._resolveFromExecutor @ vendor.js:sourcemap:5
o                               @ vendor.js:sourcemap:5
(anonymous)             @ vendor.js:sourcemap:9
o                               @ vendor.js:sourcemap:5
o._settlePromiseFromHandler @ vendor.js:sourcemap:5
o._settlePromise      @ vendor.js:sourcemap:5
o._settlePromiseCtx @ vendor.js:sourcemap:5
r._drainQueue          @ vendor.js:sourcemap:5
r._drainQueues        @ vendor.js:sourcemap:5
drainQueues            @ vendor.js:sourcemap:5
(anonymous)            @ vendor.js:sourcemap:5
vendor.js:sourcemap:15 Unhandled rejection Error: Forbidden
    at r (https://cdn02.gitter.im/_s/88aafe0/js/vendor.js:9:21524)
    at Object.error (https://cdn02.gitter.im/_s/88aafe0/js/vendor.js:9:23152)
    at l (https://cdn02.gitter.im/_s/88aafe0/js/vendor.js:3:14505)
    at Object.fireWith [as rejectWith] (https://cdn02.gitter.im/_s/88aafe0/js/vendor.js:3:15322)
    at n (https://cdn02.gitter.im/_s/88aafe0/js/vendor.js:4:20053)
    at XMLHttpRequest.<anonymous> (https://cdn02.gitter.im/_s/88aafe0/js/vendor.js:4:25961)
    at XMLHttpRequest.r (https://cdn02.gitter.im/_s/88aafe0/js/vendor.js:14:30241)
e.(anonymous function) @ vendor.js:sourcemap:15
R                          @ vendor.js:sourcemap:6
T                          @ vendor.js:sourcemap:6
S                          @ vendor.js:sourcemap:6
e._notifyUnhandledRejection @ vendor.js:sourcemap:6
r._drainQueue       @ vendor.js:sourcemap:5
r._drainQueues     @ vendor.js:sourcemap:5
drainQueues        @ vendor.js:sourcemap:5
(anonymous)        @ vendor.js:sourcemap:5
````

**Comment by jmcmurry** [comment]
For avoidance of doubt, this issue is similar but distinct from https://github.com/gitterHQ/gitter/issues/1392.
All members that are attempting to be added have their org membership public (ergo, [this caveat](https://github.com/gitterHQ/gitter/issues/1392#issuecomment-242354257) does not apply)

**Comment by mydigitalself** [comment]
@jmcmurry have you and the other members granted Private Repository Scope to Gitter on GitHub?

If you go to https://github.com/settings/applications you should see Gitter Private & Public repo apps (don't worry about Webhooks). You should be able to click on the app and see if the permission is granted to the Org as well.

**Comment by jmcmurry** [comment]
Yes, thanks. All in order. 
<img width="615" alt="screen shot 2017-06-07 at 9 42 01 am" src="https://user-images.githubusercontent.com/3658863/26890216-a31f0a3a-4b65-11e7-890e-726bec121ffe.png">

**Comment by mydigitalself** [comment]
@jmcmurry Hmm. What happens if one of them visits the URL of the room?

**Comment by jmcmurry** [comment]
Ahhh! They are prompted to upgrade the Gitter access via GitHub. When each person does this, all is well. 

It is just super confusing that the Gitter-Github access needs to be granted BOTH at the repo level AND at the person level. If this double-access restriction can't be overcome ...:

Best fix: instead of just "Forbidden", the invite should trigger an email that goes to the person and explains what they must do. (eg. visit the URL of the room and upgrade Gitter access).

Hot fix: instead of "Forbidden" message, instruct the person doing the inviting to instruct the would-be invited person to click on the room URL and upgrade their GitHub access accordingly.

**Comment by MadLittleMods** [comment]
@jmcmurry We don't have access to their email unless they have signed up on Gitter (they may have a public email but only a few do).

Improving the message is a good way to clear things up :+1:

**Comment by jmcmurry** [comment]
All of our org members are already signed up on Gitter, but perhaps in worst case, you could prompt the inviter to offer the email address. Just a thought.

**Comment by jmcmurry** [comment]
The strange thing is that the folks I'm unable to add in the NEW private repo are already on Gitter on OTHER private repos in our org. Empirically then, this config therefore would seem to need to be done done at the Org level AND for every user AND for every corresponding private repo AND each user must also all be set to 'public' status on the org membership. Seems a bit ... much, and not surprising so many people have considered this a bug. It may not be a technical failure, but it certainly is a major usability setback.

**Comment by jmcmurry** [comment]
Another level of nuance just pointed out by a team mate. 

### Permissions matrix

  _ | public Gitter room | private Gitter room
----|--------|----------------
public ORG | baseline permissions adequate | baseline permissions adequate
public REPO | baseline permissions adequate | baseline permissions adequate
private REPO | not applicable | the scenario in this ticket*

*It seems that Gitter is asking each user for "read and write all public and private repository data"; it is not clear whether this means for all private repositories in their remit, or for JUST the repository in question. Clarity from Gitter would be appreciated as my team members are understandably reluctant to issue blanket authorization to Gitter. As a workaround, I will create a private room in the public org (unassociated to the repo); repo integrations are not that important for our purposes at the moment.

**Comment by MadLittleMods** [comment]
@jmcmurry Adding private repo access applies to all of the user's repos.

**Comment by jmcmurry** [comment]
OK thanks for clarification. We're therefore definitely going to back away from this particular configuration (private repo/private gitter).
